<%@ page contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Ticket Policy | EventHorizon</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css">

    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
            font-family: "Segoe UI", Arial, sans-serif;
        }

        body {
            background: radial-gradient(circle at top left, #12002f 0%, #050816 42%, #03152a 100%);
            color: #ffffff;
            min-height: 100vh;
        }

        a {
            text-decoration: none;
            color: inherit;
        }

        .navbar {
            width: 100%;
            padding: 18px 40px;
            display: flex;
            justify-content: space-between;
            align-items: center;
            background: rgba(6, 10, 30, 0.88);
            border-bottom: 1px solid rgba(255,255,255,0.08);
            position: sticky;
            top: 0;
            z-index: 1000;
            backdrop-filter: blur(10px);
        }

        .brand {
            font-size: 2rem;
            font-weight: 800;
            letter-spacing: 1px;
            color: #7c5cff;
        }

        .nav-links {
            display: flex;
            gap: 28px;
            align-items: center;
            flex-wrap: wrap;
        }

        .nav-links a {
            color: #ffffff;
            font-size: 0.95rem;
            font-weight: 600;
            transition: 0.3s;
        }

        .nav-links a:hover {
            color: #53d8fb;
        }

        .page-wrap {
            max-width: 1100px;
            margin: 45px auto;
            padding: 0 20px 40px;
        }

        .hero-card,
        .policy-card {
            background: linear-gradient(135deg, rgba(20, 27, 61, 0.95), rgba(8, 18, 42, 0.95));
            border: 1px solid rgba(255,255,255,0.08);
            border-radius: 24px;
            padding: 30px;
            box-shadow: 0 18px 50px rgba(0,0,0,0.35);
            margin-bottom: 22px;
        }

        .hero-title {
            font-size: 2.5rem;
            font-weight: 800;
            margin-bottom: 12px;
        }

        .hero-sub,
        .policy-card p,
        .policy-card li {
            color: #d5ddf4;
            line-height: 1.9;
        }

        .policy-card h2 {
            font-size: 1.25rem;
            margin-bottom: 12px;
            color: #7fe6ff;
        }

        .policy-card ul {
            margin-left: 22px;
        }

        .footer {
            margin-top: 30px;
            text-align: center;
            color: #9fb0d9;
            font-size: 0.93rem;
            padding: 24px 10px 40px;
        }

        @media (max-width: 768px) {
            .navbar {
                flex-direction: column;
                gap: 14px;
                padding: 18px 20px;
            }

            .nav-links {
                justify-content: center;
                gap: 16px;
            }

            .hero-title {
                font-size: 2rem;
            }

            .hero-card,
            .policy-card {
                padding: 22px;
            }
        }
    </style>
</head>
<body>

<div class="navbar">
    <div class="brand">EVENTHORIZON</div>
    <div class="nav-links">
        <a href="${pageContext.request.contextPath}/index.jsp">Home</a>
        <a href="${pageContext.request.contextPath}/event?action=list">Events</a>
        <a href="${pageContext.request.contextPath}/booking?action=myBookings">My Bookings</a>
        <a href="${pageContext.request.contextPath}/profile.jsp">Profile</a>
        <a href="${pageContext.request.contextPath}/login.jsp">Login</a>
    </div>
</div>

<div class="page-wrap">
    <div class="hero-card">
        <div class="hero-title">Ticket Policy</div>
        <div class="hero-sub">
            Please read the EventHorizon ticket rules carefully before booking, paying, or attending an event.
        </div>
    </div>

    <div class="policy-card">
        <h2>1. Ticket Validity</h2>
        <p>Tickets are only valid for the specific event, ticket type, and approved booking for which they were generated.</p>
    </div>

    <div class="policy-card">
        <h2>2. Approval Requirement</h2>
        <p>Tickets may become visible only after payment verification and booking approval by the administrator.</p>
    </div>

    <div class="policy-card">
        <h2>3. QR Code Usage</h2>
        <p>Each approved ticket may be linked to a QR code for entry verification. Only valid QR codes generated by EventHorizon are accepted.</p>
    </div>

    <div class="policy-card">
        <h2>4. Non-Transferable Use</h2>
        <p>Tickets are intended for the original approved booking and should not be misused, forged, or duplicated.</p>
    </div>

    <div class="policy-card">
        <h2>5. Lost Access or Display Issues</h2>
        <p>If your ticket does not appear after approval, contact support immediately or use the issue reporting function within the platform.</p>
    </div>

    <div class="policy-card">
        <h2>6. Cancellation and Rejection</h2>
        <ul>
            <li>Rejected payments may result in booking cancellation.</li>
            <li>Cancelled bookings may invalidate related tickets.</li>
            <li>Fraudulent or incorrect submissions may lead to booking rejection.</li>
        </ul>
    </div>

    <div class="policy-card">
        <h2>7. Event Entry</h2>
        <p>Event entry is subject to valid ticket approval, successful QR verification, and event organizer rules.</p>
    </div>

    <div class="policy-card">
        <h2>8. Seat Availability</h2>
        <p>Tickets are subject to seat availability within each ticket type category. Once sold out, further booking will not be allowed for that category.</p>
    </div>

    <div class="policy-card">
        <h2>9. Policy Changes</h2>
        <p>EventHorizon may update the ticket policy when system rules, booking processes, or verification methods change.</p>
    </div>

    <div class="footer">
        © 2026 <strong>EventHorizon</strong> · Ticket Policy Page
    </div>
</div>

</body>
</html>